# -*- coding: utf-8 -*-
"""Develope machine Learning model for child mind institute detect sleep states.ipynb

Automatically generated by Colaboratory.

Original file is located at
https://www.kaggle.com/code/pragyanaianddsschool/detect-sleep-states-starter-notebook-ensemble/edit/run/171305186
"""

import pickle
import streamlit as st
import pandas as pd
from xgboost import XGBRegressor

# loading the trained model
pkl_file = open('XGBoost.pkl', 'rb')
regressor = pickle.load(pkl_file)

@st.cache_data()
# defining the function which will make the prediction using the data which the user inputs
def prediction(	hour,	anglez_times_enmo,	half_hour,	anglez,	anglez_diff,	anglez_rolling,	anglez_diff_rolling,	enmo,	enmo_diff,	enmo_rolling,	enmo_diff_rolling):
 df = pd.read_csv('/kaggle/input/zzzs-lightweight-training-dataset-target')

# Title of the app
st.title('Exploring zzzs-lightweight-training-dataset-target')

# Subtitle and basic statistics
st.write('## Dataset Overview')
st.write("Here's a quick overview of the dataset:")
st.write(df.head())  # Display the first few rows of the dataset
st.write("### Dataset Statistics:")
st.write(df.describe())  # Display basic statistics of the dataset

# Sidebar for filtering
st.sidebar.title('Filter Data')
# Add options to filter the data
filter_options = {
    "hour": "hour",
    "anglez_times_enmo": "anglez_times_enmo",
    "half_hour": "half_hour",
    "anglez": "anglez",
    "anglez_diff": "anglez_diff",
    "anglez_rolling": "anglez_rolling",
    "	anglez_diff_rolling": "	anglez_diff_rolling",
    "enmo": "enmo",
    "enmo_diff":"enmo_diff",
    "enmo_rolling": "henmo_rolling",
    "	enmo_diff_rolling": "	enmo_diff_rolling"
}
selected_column = st.sidebar.selectbox("Select a column to filter:", list(filter_options.keys()))

# Filter the data based on user selection
selected_value = st.sidebar.text_input(f"Enter the value for {selected_column}:", "")
filtered_data = df[df[selected_column] == selected_value]

# Display the filtered data
st.write("### Filtered Data:")
st.write(filtered_data)

# Visualize the data
st.write("## Data Visualization")
st.write("### Bar Chart of Column 1")
# You can create different types of visualizations here
# For example, a bar chart of counts for 'Column 1'
bar_chart_data = df['column1'].value_counts() 
st.bar_chart(bar_chart_data)

# Interactive plotting with Plotly (optional)
st.write("### Interactive Plot with Plotly")
import plotly.express as px
fig = px.scatter(df, x='column1', y='column2', color='target')
st.plotly_chart(fig)

# Add more features and visualizations as needed

# Footer
st.write("---")
st.write("Created with Streamlit - A Simple and Interactive Way to Explore Data")

    # when 'Predict' is clicked, make the prediction and store it
    if st.button("Predict"):
        result = prediction(hour,	anglez_times_enmo,	half_hour,	anglez,	anglez_diff,	anglez_rolling,	anglez_diff_rolling,	enmo,	enmo_diff,	enmo_rolling,	enmo_diff_rolling)

        st.success('Your Sleep state Prediction is {}'.format(result))
        print(result)

if __name__=='__main__':
    main()
